### ISSUE TITLE
Do I have to use bun to contribute to the translation of the website?

### ISSUE THREAD

**Issue by ShiMeiWo** [quinton-ashley/p5play-web#15]
I came here after finding a Japanese version on the home page (I am Japanese and a Japanese speaker).

On the project's project-planning-page, "home page and learn pages translated to Spanish and Japanese." is marked "Done!", but there are some untranslated, mistranslated, or confusing expressions in some Japanese pages. If you don't mind, I would like to help with the translation.

However, I have one concern. Is it necessary to use bun instead of Node.js as the runtime? I am a Windows 10 user and bun does not work well on my PC, so I would appreciate it if you could clarify that first.

**Comment by quinton-ashley** [comment]
bun actually can't be used for the translations so all good! Here are the instructions, sorry I should've added a link for this in the readme.

https://github.com/quinton-ashley/p5play-web/blob/main/lang/instructions.md

I would really appreciate your help!

**Comment by ShiMeiWo** [comment]
I started the revision from the Sprite section like this:
https://github.com/ShiMeiWo/p5play-web/compare/main...ShiMeiWo:p5play-web:develop?expand=1

I will push progress to my develop branch as needed. When I have finished with each section, I will merge it into the main branch, squash it, and send you a PR.

If you have any comments or questions, please contact me.

**Comment by quinton-ashley** [comment]
Awesome! Yeah you can send the PR now for the sprite pages and I'll update the site.

**Comment by ShiMeiWo** [comment]
The PR have been submitted and can be peer-reviewed at DeepL or ChatGPT at your convenience to determine if they can be merged or not.
