### ISSUE TITLE
Darkmode makes text unreadable

### ISSUE THREAD

**Issue by awdriggs** [quinton-ashley/p5play-web#2]
Seems like there was a recent change to make the website be in "dark mode." This has made reading the examples on the learn pages next to impossible.
<img width="521" alt="image" src="https://user-images.githubusercontent.com/1815808/201482596-1952f4a8-834c-422e-a290-e87b63a8af29.png">
Am I missing something? Is there a way to toggle between darkmode and light mode?

I'm working with chrome browser Version 107.0.5304.110 (Official Build) (x86_64). But same thing is happening with safari on a macbook and on an ipad.

**Comment by quinton-ashley** [comment]
thank you for reporting this! Just fixed it. I'm going to add the night/day mode toggle too
