### ISSUE TITLE
[translation] What does "run the function multiple times" mean?

### ISSUE THREAD

**Issue by ShiMeiWo** [quinton-ashley/p5play-web#21]
I have a question about the translation of the World chapter.

On the "Controlling Time page", the original says:

> If you want to advance the simulation by a larger amount of time, run the `world.step` function multiple times.

Which of the following does this "run the `world.step` function multiple times." mean?

A: "run the `world.step` function more than once."

```js
function draw() {
  background(0);
  
  world.step();
  world.step();
  world.step();
  world.step();
}
```

B: "run the `world.step` function with multiple number of times given as an argument."

```js
function draw() {
  background(0);
  
  world.step(4);
}
```

I would appreciate it if you could let me know the difference, as the translation will vary depending on this difference.

Thanks!

**Comment by quinton-ashley** [comment]
Yeah it would be more than once!
