### ISSUE TITLE
[translation] "Although this example woud benefit ~" in Tile chapter

### ISSUE THREAD

**Issue by ShiMeiWo** [quinton-ashley/p5play-web#22]
I have a question about the last paragraph in Tile chapter.

The original says:

> Although this example would benefit from input buffering to ensure the player completes a move before starting another.

But, I could not quite grasp the meaning of this sentence. From the context of the text and the behavior of the mini-example, I infer this way:

> In this example, however, you should benefit from input buffering to ensure that the player's movement of "one tile" is complete before starting the next.

Is this a correct interpretation? If it means something different, please let me know.

Thanks!

**Comment by quinton-ashley** [comment]
Here's a rewrite that I think is more clear:

This code example could be improved by adding input buffering, to ensure that the player completes one move before starting another.

**Comment by ShiMeiWo** [comment]
Thank you for your explanation and rewriting!

> This code example could be improved by adding input buffering, to ensure that the player completes one move before starting another.

In Japan, the word "buffer" (バッファ [baffa]) generally means "a storage area where data is temporarily saved" (which implies "to retrieve and use the data later") rather than original "a cushioning to protect against the interruption of data flow". Therefore, I would like to add to this term the description "a process that temporarily prevents" and "during the move", like:

> This code example could be improved by adding key input buffering (a process that temporarily prevents) during the move, to ensure that the player completes one move before starting another.

Can I translate as above?

Thanks!

**Comment by quinton-ashley** [comment]
yup that sounds good!
