### ISSUE TITLE
p5play no longer works p5js

### ISSUE THREAD

**Issue by gfairSG** [quinton-ashley/p5play-web#24]
Just a month or so ago all was working wonderfully in the p5js editor.

Now it throws errors for new Canvas...

Even the starter code
https://editor.p5js.org/quinton-ashley/sketches/szN_XdV5O
fails with this p5js error:

> ReferenceError: Canvas is not defined
>     at setup (/sketch.js:12:3)
>     at _setup (https://cdn.jsdelivr.net/npm/p5@1.9.0/lib/p5.js:63319:25)
>     at _runIfPreloadsAreDone (https://cdn.jsdelivr.net/npm/p5@1.9.0/lib/p5.js:63265:27)
>     at p5._decrementPreload (https://cdn.jsdelivr.net/npm/p5@1.9.0/lib/p5.js:63276:25)
>     at p5.<anonymous> (https://cdn.jsdelivr.net/npm/p5@1.9.0/lib/addons/p5.sound.min.js:2:98292)

Is there a way to fix this?

**Comment by quinton-ashley** [comment]
The only problem is with the p5js web editor. I'm not affiliated with the Processing Foundation so I can't do anything about it. Please make an error report to them but unfortunately they can be very slow with fixes. I recommend trying aijs.io

**Comment by gfairSG** [comment]
Hi Quinton,

Thank you for your quick response.

With your p5play template in p5js it fails but Jessie’s is working fine.

https://editor.p5js.org/jesse_harding/sketches/LCvBXl0bX

It looks like they're using the same libraries but loads Planck first.

Could it be as simple as that?

Gordon

**Comment by quinton-ashley** [comment]
ah! Yup that did the trick
