### ISSUE TITLE
Broken link on "Game Jam" page

### ISSUE THREAD

**Issue by ShiMeiWo** [quinton-ashley/p5play-web#27]
In the original "Puzzling Magnetism Recharged" introduction, the link to the code (`https://v6p9d9t4.ssl.hwcdn.net/html/7146864/sketch.js`) gives a 404 error, can I just describe it as is?

**Comment by quinton-ashley** [comment]
Thanks for noting that. It must've been a temporary link. I'll host a copy of the code on p5play.org for reference and change that link.

**Comment by quinton-ashley** [comment]
okay I looked into it and this is the new link to that code!

https://html-classic.itch.zone/html/7146864/sketch.js
