### ISSUE TITLE
 Links to questKid image are broken on non-English sites.

### ISSUE THREAD

**Issue by ShiMeiWo** [quinton-ashley/p5play-web#29]
The link to questKid image on the: 

- Learn
  - Ani
    - Sprite Sheets with Multiple Animations <- here!

page functions correctly in the English version, but result in `404` errors on the Spanish and Japanese versions of the page.

ex)

![image](https://github.com/quinton-ashley/p5play-web/assets/11846146/8759dc5b-486b-4d71-9764-c8e0737ded34)

Please check the site-generator.

Thanks!

**Comment by quinton-ashley** [comment]
thanks for reporting! just fixed it
