### ISSUE TITLE
[css] The "Created by Quinton Ashley" section of the top page on smartphones is sticking out at the top and bottom.

### ISSUE THREAD

**Issue by ShiMeiWo** [quinton-ashley/p5play-web#36]
ref: https://github.com/quinton-ashley/p5play-web/pull/34#issuecomment-2063086625

In non-English language displays, the "Created by Quinton Ashley" section is overhanging the display area. Possible solutions to the problem are as follows:

# 1. To change `#md15` element into scrollable container:

```css
@media screen and (max-width: 1030px) {
  /* snip! */

  #md15 {
      height: calc(100% - 2rem);
      overflow-y: auto;
  }
}
```

![image](https://github.com/quinton-ashley/p5play-web/assets/11846146/0dc2eabb-3b99-463a-9b81-060e0e8fb7d0)

# 2. To add `{position: relative; height: auto}` style at the parent element of `img{position: absolute; height: auto}` to fix the origin of coordinate and calculate imase position:

## es)

![image](https://github.com/quinton-ashley/p5play-web/assets/11846146/1d7bfa37-8587-4cd0-999a-6b617deff8b6)
 
## ja)

![image](https://github.com/quinton-ashley/p5play-web/assets/11846146/45342da0-cc59-4be9-9c20-d6f3c5a60fb4)

## en)

![image](https://github.com/quinton-ashley/p5play-web/assets/11846146/728dc768-93f1-4243-a743-24f022e2121f)

# 3. To change the background photo to be represented by the container's `background` instead of `img`:

## es)

![image](https://github.com/quinton-ashley/p5play-web/assets/11846146/170fbdb0-c216-4055-a085-7a266db8d5ed)

## ja)

![image](https://github.com/quinton-ashley/p5play-web/assets/11846146/7486c700-6066-46fa-b6ab-149a455b5d1f)

## en)

![image](https://github.com/quinton-ashley/p5play-web/assets/11846146/0421759c-5309-4a0a-983e-da1dac9656cd)

# Conclusion

The easiest way is `#1`, but the drawback is that they have to scroll to see the full text. As a front-end developer, I'd love with `#3`, but if it has to be an `<img>` for accessibility reasons, then it's not a candidate. `#2` requires more CSS modifications and calculations, but is a good balance between markup and look-and-feel.

If without the aesthetic requirements, I would recommend `#1`. Please let me know what you think.

Thanks!

**Comment by ShiMeiWo** [comment]
@quinton-ashley 

![image](https://github.com/quinton-ashley/p5play-web/assets/11846146/7eed5a83-2f8f-46d8-92ae-5b7a1924a974)

Understood. Then, I will adopt #1.

Thank you for your patience...

**Comment by quinton-ashley** [comment]
sorry I liked your post but forgot to respond! I want to try option 3 but will merge your PR for now. Thank you!

**Comment by ShiMeiWo** [comment]
@quinton-ashley Okay, I will try `#3` (display "the Ashleys image" as the element's background).

How about markup `<img>` ? Can I remove it? Otherwise, I will conceal it with `{display: none;}` etc.
