### ISSUE TITLE
[translation] About the name of Ms. Ye.

### ISSUE THREAD

**Issue by ShiMeiWo** [quinton-ashley/p5play-web#41]
In `activism.md` , I see the name "Qianqian Ye", is this the same person as the URL below?

https://qianqian-ye.com/about.html

If so, her original name is "Ye Qianqian" (叶 千千). We, the CJK people, say our names in the order of "family name -> personal name" but when introducing ourselves in Western Europe, the order is sometimes flipped to "personal name -> family name" to suit the locale (ex: Shi MeiWo -> MeiWo Shi). 

Also, in Japan, the use of a foreigner's name is based on the principle of reciprocity between nations, so "叶 千千" is pronounced "Kyō Sensen" (きょう・せんせん), not "Ye Qianqian" (いぇ・ちぇんちぇん).

So, can I translate her name as below?

> USC professor, Qianqian Ye 

 ↓

> 南カリフォルニア大学教授、叶 千千（きょう・せんせん / Ye Qianqian）氏

Thanks!

**Comment by quinton-ashley** [comment]
Yes thank you!
