### ISSUE TITLE
In non-English language versions, the link to Sign Up on the pop-up is incorrect.

### ISSUE THREAD

**Issue by ShiMeiWo** [quinton-ashley/p5play-web#45]
English ver.:  `/pro/signup.html`

Non-English ver.: `/lang/(langCode)/pro/signup.html`

https://github.com/quinton-ashley/p5play-web/assets/11846146/6dac3ba3-69c5-44a0-be78-c81b8a0480fc

Thanks!

**Comment by quinton-ashley** [comment]
thanks for reporting, just fixed this

Now I'll need to work on supporting translations on the signup page itself!
