### ISSUE TITLE
Learn pages require login

### ISSUE THREAD

**Issue by Pilen** [quinton-ashley/p5play-web#47]
Hi, For a while I have been evaulating using p5play as a tool for teaching kids to program and develop games in a small "makerspace" i am managing.

Lately I have noticed several of the documentation pages requires login to be used. This seems rather detrimental to the adoption.
If it was only me going to use it, i could just make and use an account, but it seems rather cumbersome to manage an account for each kid, and i'm not sure about having a single shared account.

Do you really intent to require a login for referencing the documentation?

**Comment by quinton-ashley** [comment]
p5play's full documentation doesn't require a login:
https://p5play.org/docs/Sprite.html

The Learn reference pages do require a login. It only takes a minute for
students to sign up for an account, which they can do on their own no need
for account management. I'm also going to make logins valid for a month.

I started requiring logins so I could ensure that teachers are paying to
use the Learn pages.

**Comment by ShiMeiWo** [comment]
@quinton-ashley

Actually, in a case like @Pilen 's, does it fall under _PRO$_ ?

**Comment by quinton-ashley** [comment]
If he's getting paid to teach at the makerspace, then yes. But I assume its just a club, so they could use the Learn pages without paying.
