### ISSUE TITLE
[Translation] About the term "Equitable Access"

### ISSUE THREAD

**Issue by ShiMeiWo** [quinton-ashley/p5play-web#53]
In the `pro/index.md` file, I found a new heading, "Equitable Access" (/ékwəṭəbl ˈækses/).

Since this term is not yet familiar in Japan, I believe it is necessary to rephrase it in another language for translation. According to https://www.slingshotedu.com/blog/what-is-equitable-access , the term means "equalization of educational opportunities for the purpose of realizing academic freedom", so I have the following proposed translation.

1. 教育機会の均等化（エクイタブル・アクセス）にむけて
    - lit: **For "Equal educational opportunity" (Ekuitaburu Akusesu)**
    - Kinda descriptive translation.
1. 平等な学び（エクイタブル・アクセス）のために
    - lit: **For "Learning for All" (Ekuitaburu Akusesu)**
    - A free translation with coined phrase ("Learning for All") by me.
1. 経済的困窮者の方へのご案内
    - lit: **For the economically needy**
    - Give up translating the words and instead prioritize its function as a heading.

I would prefer proposal 1. What is your opinion, Mr. Ashley?

Thanks!

**Comment by ShiMeiWo** [comment]
@quinton-ashley 
>  I'm working on a big update to the website. I'll let you know when it's released.

That's huge news! I eagerly await the release of the update!

**Comment by quinton-ashley** [comment]
@ShiMeiWo I just published the first part of the update today, improving the p5play.org/teach page.

I still need to make it so the headers can be replaced with translated text.

Next I will update the p5play.org/pro page.

By the way, I will give you free Pro membership or educational access since you've helped with the translation!

**Comment by ShiMeiWo** [comment]
@quinton-ashley 
> I just published the first part of the update today, improving the p5play.org/teach page.

Okay, I'll translate p5play.org/teach.md ASAP.

**Comment by quinton-ashley** [comment]
@ShiMeiWo Thanks! What email did you use for your p5play.org account?

**Comment by quinton-ashley** [comment]
yea good idea, my twitter is p5play_js

**Comment by ShiMeiWo** [comment]
@quinton-ashley I tried to send a direct message to p5play_js, but the account seems to be set to reject incoming messages. Please check your settings.

Please note that until I can send direct messages, I will keep my account (`@Shi_MeiWo`) in public status just in case.

![image](https://github.com/user-attachments/assets/c001e770-fea8-4514-b75b-0ea4b10d6c21)

**Comment by quinton-ashley** [comment]
You were right. Not sure how that happened, just changed it to accept messages from anyone. I will message you.

**Comment by ShiMeiWo** [comment]
I was able to receive your email with the email address I gave you the other day without any problem.

Thanks!
