### ISSUE TITLE
non-English webpages getting 404 errors

### ISSUE THREAD

**Issue by shibomb** [quinton-ashley/p5play-web#9]
After switching to Spanish and Japanese pages, I am getting 404 errors on link various pages in the header.
For example, each URL is as follows:
https://p5play.org/lang/ja/lang/es

This is probably because the links are relative paths.

Wouldn't it be better to make the page links full paths from the root?

(The path to favicon seems to have the same error.)

Best regards.

**Comment by quinton-ashley** [comment]
Thank you! Good catch and wow I didn't even know that was possible. I'm going to refactor the whole website to use root paths.

**Comment by quinton-ashley** [comment]
done!
